[build]
  publish = "dist"
  command = "npm run build"

# Handle SPA routing by redirecting all paths to index.html with 200 status
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Cache control for static assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline'; img-src 'self' data:; font-src 'self'; connect-src 'self'"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"

# Build environment variables
[build.environment]
  NODE_VERSION = "18"

# Production context configuration
[context.production]
  # Set custom domain and other production environment variables
  environment = { 
    NODE_VERSION = "18",
    NETLIFY_CUSTOM_DOMAIN = "prompt-generator.melihcandemir.netlify.app" 
  } 